# Generated by Django 4.0.3 on 2023-06-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viewdata',
            new_name='Student',
        ),
    ]
